[project]
name = "music-royalty-derivatives"
description = "Trade future music earnings as financial instruments"
authors = ["p73908140"]
telemetry = true
cache_dir = "./.cache"

[[project.contracts]]
name = "music-royalty-derivatives"
path = "contracts/music-royalty-derivatives.clar"
clarity_version = 2
epoch = "2.4"